[package]
name = "seek-local"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
tokio = { version = "1.43.0", features = [ "macros", "rt-multi-thread" ] }
axum = { version = "0.8.1", features = [ "macros" ] }
serde = { version = "1.0.217", features = [ "derive" ] }